{% set version = "1.12.0" %}

package:
  name: iris
  version: {{ version }}

source:
  fn: iris-v{{ version }}.tar.gz
  url: https://github.com/SciTools/iris/archive/v{{ version }}.tar.gz
  sha256: 62e4cb152366e21aa845f1fbf0520abda39ccc7c5952e6a434eed5cd9f2cc140
  patches:
    # Issue reported in https://github.com/SciTools/iris/issues/2004.
    # We work around this in build.sh.
    - no_compile_setup.patch  # [osx]

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - biggus >=0.14
    - cartopy >=0.14
    # See https://github.com/SciTools/iris/issues/2322
    - netcdf4 <=1.2.4
    - cf_units
    - pyke
    - mo_pack  # [not win]
    - nc_time_axis
    - iris-grib  # [not (win or py3k)]
  run:
    - python
    - numpy
    - scipy
    - biggus >=0.14
    - cartopy >=0.14
    # See https://github.com/SciTools/iris/issues/2322
    - netcdf4 <=1.2.4
    - cf_units
    - pyke
    - mo_pack  # [not win]
    - matplotlib <2
    - nc_time_axis
    - iris-grib  # [not (win or py3k)]

test:
  imports:
    - iris
    - iris.fileformats._pyke_rules.compiled_krb

about:
  home: http://www.scitools.org.uk/iris
  license: GPL3
  license_family: GPL3
  license_file: README.md
  summary: 'Analyse and visualise meteorological and oceanographic data sets.'

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
    - bjlittle
